/**
 * Activity Log → PDF exporter (jsPDF, manual layout).
 *
 * Text-only, print-friendly. Wordmark drawn as two-color text.
 * Page header + footer on every page, filter context on page 1,
 * grouped entries with no mid-entry page breaks.
 */
import { jsPDF } from "jspdf";
import { format } from "date-fns";

export interface ActivityPdfRow {
  id: string;
  ts: Date;
  actorDisplayName: string;
  pre: string;               // text between actor and project (e.g. "moved ")
  projectLabel: string;      // "Customer · Project Name" / fallback
  post: string;              // text after project (e.g. " from X → Y")
  astTime: string;           // "3:09 AM AST"
}

export interface ActivityPdfGroup {
  label: string;
  rows: ActivityPdfRow[];
}

export interface ActivityPdfFilters {
  member: string;            // "" = all
  search: string;            // "" = none
  dateRangeLabel: string;    // "All time" / "Last 7 days" / "Apr 1 – Apr 30"
  totalCount: number;
}

const NAVY: [number, number, number] = [27, 42, 78];          // #1B2A4E
const ORANGE: [number, number, number] = [233, 123, 44];      // #E97B2C
const MUTED: [number, number, number] = [120, 120, 130];
const LINE: [number, number, number] = [220, 220, 225];

const PAGE = { w: 595.28, h: 841.89 };  // A4 portrait pts
const M = { top: 54, bottom: 54, left: 54, right: 54 }; // ~0.75"
const CONTENT_W = PAGE.w - M.left - M.right;

export function exportActivityPdf(
  groups: ActivityPdfGroup[],
  filters: ActivityPdfFilters,
): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const generatedAt = new Date();
  const generatedLabel = `Generated ${format(generatedAt, "EEE d MMM yyyy, h:mm a")}`;

  let y = 0;
  let pageNum = 1;

  // Header drawn after pages exist; we'll render header + footer on each page
  // at the end via a second pass using internal page count.
  const drawPageChrome = (pageIndex: number, totalPages: number) => {
    doc.setPage(pageIndex);
    // Wordmark "alvas" + "co"
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(...NAVY);
    doc.text("alvas", M.left, 36);
    const alvasW = doc.getTextWidth("alvas");
    doc.setTextColor(...ORANGE);
    doc.text("co", M.left + alvasW, 36);

    // Title centered-ish (left of generated label)
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(...NAVY);
    const titleX = M.left + 110;
    doc.text("Activity Log", titleX, 36);

    // Generated timestamp top-right
    doc.setFontSize(8.5);
    doc.setTextColor(...MUTED);
    const genW = doc.getTextWidth(generatedLabel);
    doc.text(generatedLabel, PAGE.w - M.right - genW, 36);

    // Header rule
    doc.setDrawColor(...LINE);
    doc.setLineWidth(0.5);
    doc.line(M.left, 46, PAGE.w - M.right, 46);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    const footer = "Generated by Alvasco ERP · Confidential";
    const fW = doc.getTextWidth(footer);
    doc.text(footer, (PAGE.w - fW) / 2, PAGE.h - 24);
    const pageLabel = `Page ${pageIndex} of ${totalPages}`;
    const pW = doc.getTextWidth(pageLabel);
    doc.text(pageLabel, PAGE.w - M.right - pW, PAGE.h - 24);
  };

  // Body cursor starts below header area
  const TOP_BODY = 70;
  const BOTTOM_LIMIT = PAGE.h - M.bottom - 8;
  y = TOP_BODY;

  // Filter context block (page 1 only)
  const filterParts: string[] = [];
  if (filters.member) filterParts.push(filters.member);
  else filterParts.push("All team members");
  filterParts.push(filters.dateRangeLabel || "All time");
  if (filters.search) filterParts.push(`Search: "${filters.search}"`);
  const isFiltered = filters.member || filters.search || (filters.dateRangeLabel && filters.dateRangeLabel !== "All time");
  const filterLine = isFiltered
    ? `Filtered by: ${filterParts.join(" · ")}`
    : "All activity · All team members · All time";

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...NAVY);
  doc.text(filterLine, M.left, y);
  y += 14;
  doc.setTextColor(...MUTED);
  doc.setFontSize(9);
  doc.text(`${filters.totalCount.toLocaleString()} ${filters.totalCount === 1 ? "entry" : "entries"}`, M.left, y);
  y += 18;
  doc.setDrawColor(...LINE);
  doc.line(M.left, y, PAGE.w - M.right, y);
  y += 14;

  const ensureSpace = (needed: number) => {
    if (y + needed > BOTTOM_LIMIT) {
      doc.addPage();
      pageNum++;
      y = TOP_BODY;
    }
  };

  // Group + rows
  for (const g of groups) {
    if (g.rows.length === 0) continue;

    // Group header
    ensureSpace(28);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...NAVY);
    doc.text(g.label.toUpperCase(), M.left, y);
    y += 12;
    doc.setDrawColor(...LINE);
    doc.line(M.left, y, PAGE.w - M.right, y);
    y += 10;

    for (const r of g.rows) {
      // Build wrapped line(s)
      const today = new Date(); today.setHours(0, 0, 0, 0);
      const isToday = r.ts.getTime() >= today.getTime();
      const timeStr = isToday
        ? format(r.ts, "h:mm a")
        : format(r.ts, "MMM d, h:mm a");

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);

      const TIME_W = 78;
      const bodyX = M.left + TIME_W + 8;
      const bodyW = CONTENT_W - TIME_W - 8;

      // Compose body text — name bold + rest regular. We'll split into
      // segments and measure width while wrapping.
      const segments: { text: string; bold: boolean }[] = [
        { text: r.actorDisplayName + " ", bold: true },
        { text: r.description, bold: false },
      ];
      if (r.projectLabel) {
        segments.push({ text: ` · ${r.projectLabel}`, bold: false });
      }

      // Naive wrapping by words
      const lines: { text: string; bold: boolean }[][] = [[]];
      let curW = 0;
      for (const seg of segments) {
        const words = seg.text.split(/(\s+)/);
        for (const w of words) {
          if (!w) continue;
          doc.setFont("helvetica", seg.bold ? "bold" : "normal");
          const ww = doc.getTextWidth(w);
          if (curW + ww > bodyW && lines[lines.length - 1].length > 0) {
            lines.push([]);
            curW = 0;
            if (/^\s+$/.test(w)) continue; // skip leading whitespace
          }
          lines[lines.length - 1].push({ text: w, bold: seg.bold });
          curW += ww;
        }
      }

      const lineHeight = 13;
      const blockH = Math.max(lineHeight, lines.length * lineHeight) + 6;
      ensureSpace(blockH);

      // Time (left col)
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(...MUTED);
      doc.text(timeStr, M.left, y);

      // Body lines
      doc.setFontSize(10);
      doc.setTextColor(...NAVY);
      let cursorX = bodyX;
      let lineY = y;
      for (let li = 0; li < lines.length; li++) {
        cursorX = bodyX;
        for (const tok of lines[li]) {
          doc.setFont("helvetica", tok.bold ? "bold" : "normal");
          doc.text(tok.text, cursorX, lineY);
          cursorX += doc.getTextWidth(tok.text);
        }
        lineY += lineHeight;
      }

      y += Math.max(lineHeight, lines.length * lineHeight) + 6;

      // Separator
      doc.setDrawColor(240, 240, 244);
      doc.setLineWidth(0.3);
      doc.line(M.left, y - 2, PAGE.w - M.right, y - 2);
      y += 4;
    }

    y += 4;
  }

  // Second pass: draw chrome on every page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) drawPageChrome(i, totalPages);

  doc.save(`alvasco-activity-log-${format(generatedAt, "yyyy-MM-dd")}.pdf`);
}
